# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- developer

pool:
  vmImage: 'ubuntu-latest'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'HardwareIntrinsics.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'HardwareIntrinsics.sln'